version: 2.1
orbs:
  gh-pages: sugarshin/gh-pages@0.0.6
jobs:
  build:
    docker:
      - image: barichello/godot-ci
    steps:
      - checkout
      - run:
          name: Prepare build directory
          command: mkdir -v -p ./build/web
      - run:
          name: Export HTML5 preset
          command: godot -v --export "HTML5" ./build/web/index.html
      - persist_to_workspace:
          root: build
          paths:
            - web
      - store_artifacts:
          path: ./build/web/
      

workflows:
    "Build and deploy to Github Pages!":
        jobs:
          - build
          - gh-pages/deploy:
              build-dir: build/web
              workspace-root: build
              requires:
                - build
              ssh-fingerprints: '48:7c:78:43:e3:26:5b:a8:5a:00:ae:0b:25:c5:14:84'