name: Build app

on:
  push:
    branches:
      - master

env:
  BUILD_NAME: asteroids-2
  BUILD_PATH: exports/HTML5

jobs:
  export:
    name: Checkout and build for web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Export web
        uses: firebelley/godot-export@v1.2.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_linux_headless.64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/3.1.2/Godot_v3.1.2-stable_export_templates.tpz
          godot_template_version: 3.2.1.stable
          relative_project_path: ./
          create_release: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Log
        run: ls -al exports

      - name: Deploy to Github Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v1.3.0
        with:
          build_dir: ${{ env.BUILD_PATH }}
          keep_history: true # This allows us to rollback gh-pages, defaults to false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}

      - name: Upload web artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.BUILD_NAME }}
          path: ${{ env.BUILD_PATH }}
